### ISSUE TITLE
CoreProtect

### ISSUE THREAD

**Issue by TheChampTF** [SBPrime/BlocksHub#14]
Hey

Core protect just got updated.

Now getting:

[Server thread/WARN]: [AsyncWorldEdit] Task #98 for AsyncWorldEdit v2.2.1 generated an exception
java.lang.NoSuchMethodError: net.coreprotect.CoreProtectAPI.logRemoval(Ljava/lang/String;Lorg/bukkit/Location;IB)Z
	at org.PrimeSoft.blocksHub.coreProtect.CoreProtectLogger.logBlock(CoreProtectLogger.java:115) ~[?:?]
	at org.PrimeSoft.blocksHub.Logic.logBlock(Logic.java:241) ~[?:?]
	at org.primesoft.asyncworldedit.BlocksHubIntegration.logBlock(BlocksHubIntegration.java:104) ~[?:?]
	at org.primesoft.asyncworldedit.BlocksHubIntegration.logBlock(BlocksHubIntegration.java:172) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.logBlock(AsyncWorld.java:1019) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld.access$000(AsyncWorld.java:90) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$8.execute(AsyncWorld.java:279) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.world.AsyncWorld$8.execute(AsyncWorld.java:267) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.entries.WorldExtentFuncEntryEx.process(WorldExtentFuncEntryEx.java:73) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.processQueue(BlockPlacer.java:344) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.run(BlockPlacer.java:296) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.access$000(BlockPlacer.java:69) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer$1.run(BlockPlacer.java:206) ~[?:?]
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacerTask$1.run(BlockPlacerTask.java:75) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:53) ~[custom.jar:git-Bukkit-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [custom.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:677) [custom.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336) [custom.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626) [custom.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534) [custom.jar:git-Bukkit-0a645a2]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

**Comment by NextGenDan** [comment]
I've submitted a pull request that fixes this issue here: https://github.com/SBPrime/BlocksHub/pull/15

**Comment by TheChampTF** [comment]
Okay, lets hope it's get approved shortly (:

**Comment by TheChampTF** [comment]
Problem fixed, thanks
