### ISSUE TITLE
Blockshub-Coreprotect

### ISSUE THREAD

**Issue by skippyaut** [SBPrime/BlocksHub#20]
Does not work on latest version from Coreprotect

[07:51:37] [Server thread/ERROR]: Could not load 'plugins/BlocksHub-CoreProtect.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: BlocksHub
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot.jar:git-Spigot-944aa20-8d16fc0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]

**Comment by SBPrime** [comment]
You need to install BlockHub core plugin.
