### ISSUE TITLE
BlocksHub-CoreProtect

### ISSUE THREAD

**Issue by TheChampTF** [SBPrime/BlocksHub#8]
Minecraft Version: 1.8
Operating System: Linux (amd64) version 2.6.38-8-server
Java Version: 1.8.0_31, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 4562271664 bytes (4350 MB) / 6259474432 bytes (5969 MB) up to 6259474432 bytes (5969 MB)

Running: CraftBukkit version git-Bukkit-e81edfc (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

[14:39:53 ERROR]: Could not load 'plugins/BlocksHub-CoreProtect.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: CoreProtect
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit.jar:git-Bukkit-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit.jar:git-Bukkit-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.<init>(CraftServer.java:250) [craftbukkit.jar:git-Bukkit-e81edfc]
	at net.minecraft.server.v1_8_R1.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-e81edfc]
	at net.minecraft.server.v1_8_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-e81edfc]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:133) [craftbukkit.jar:git-Bukkit-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:484) [craftbukkit.jar:git-Bukkit-e81edfc]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

**Comment by SBPrime** [comment]
The error means you did not install CoreProtect. I do not know what do you expect. Please provide details.

**Comment by TheChampTF** [comment]
Issue found.
